### ISSUE TITLE
[Bug] Broken link in Python examples readme

### ISSUE THREAD

**Issue by jscarb70** [temporalio/samples-python#127]
### What are you really trying to do?

See how to set up a local server.  (In particular, I want to see if my docker-compose setup will suffice for this)

### Describe the bug

[Local Temporal server running](https://docs.temporal.io/application-development/foundations#run-a-development-cluster) is on the [readme](https://github.com/temporalio/samples-python/?tab=readme-ov-file).  Click the link and it goes to a 404 page. 

### Minimal Reproduction
1. 
![image](https://github.com/user-attachments/assets/6566d23b-95fb-4973-908e-ba0120f16994)
Click "Local Temporal server running".
2. 
![image](https://github.com/user-attachments/assets/9dcfa07e-6f0d-44ae-bfb6-fa7df81638d2)
Page not found

**Comment by cretz** [comment]
We will fix, thanks!
