### ISSUE TITLE
Sample request: DSL

### ISSUE THREAD

**Issue by cretz** [temporalio/samples-python#7]
* https://github.com/temporalio/samples-go/tree/main/dsl
* https://github.com/temporalio/samples-typescript/tree/main/dsl-interpreter

**Comment by ravi-selvaraj** [comment]
+1 for requesting a Python sample using DSL

**Comment by benkevan** [comment]
Not a fan of +1 in general, but, +1 for this!

**Comment by JobaDiniz** [comment]
We need this sample for dotnet

**Comment by cretz** [comment]
There is an open issue at https://github.com/temporalio/samples-dotnet/issues/19
