### ISSUE TITLE
[Bug] Activity sticky queue example written incorrectly

### ISSUE THREAD

**Issue by cretz** [temporalio/samples-python#70]
### Describe the bug

The sample has a select-task-queue activity that uses a random set of task queues. But it's supposed to return a fixed task queue for the host its on. See the TypeScript sample it references.

**Comment by cretz** [comment]
cc @Oracen

**Comment by Oracen** [comment]
Took a look at the node example - I assumed the original intent was to emphasise the sticky activity, not locking both activity and workflow to the one host. That's on me. Will bang in a fix this evening.

**Comment by cretz** [comment]
Thanks a lot, we appreciate it!
